apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ashu-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3-csi