apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ashu-pod1
  name: ashu-pod1
spec:
  volumes: 
  - name: ashu-vol1 
    persistentVolumeClaim:
      claimName: ashu-pvc 
  containers:
  - image: nginx
    name: ashu-pod1
    ports:
    - containerPort: 80
    volumeMounts: 
    - name: ashu-vol1 
      mountPath: /mnt/data
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
